import { createHash } from 'node:crypto';
import { createReadStream, existsSync, mkdirSync, cpSync, rmSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';
const root=dirname(dirname(fileURLToPath(import.meta.url))), notesRoot=root;
const blogCandidates=[process.env.HALOMOON_BLOG_DIR,join(root,'.halomoon-build','HolyLinux'),'D:\\aaaaWordSpace\\HolyLinux-Astro','C:\\Users\\G15\\Documents\\Codex\\2026-09-16\\woxi\\outputs\\HolyLinux-Astro'].filter(Boolean);
const host=process.env.HALOMOON_DEPLOY_HOST||'47.116.62.248', user=process.env.HALOMOON_DEPLOY_USER||'halomoon';
const key=process.env.HALOMOON_DEPLOY_KEY_FILE||'C:\\Users\\G15\\Documents\\Codex\\2026-09-16\\woxi\\work\\halomoon-actions-ed25519';
const known=process.env.HALOMOON_KNOWN_HOSTS_FILE||'C:\\Users\\G15\\Documents\\Codex\\2026-09-16\\woxi\\work\\halomoon-known-hosts';
function run(c,a,w,e=process.env){const r=spawnSync(c,a,{cwd:w,env:e,stdio:'inherit',shell:false});if(r.error)throw r.error;if(r.status)throw Error(c+' exit '+r.status)}
function cap(c,a,w,t){return new Promise((ok,no)=>{const x=spawn(c,a,{cwd:w,shell:false,stdio:['ignore','pipe','inherit']});let o='';x.stdout.on('data',b=>o+=b);const timer=setTimeout(()=>{x.kill();no(Error(c+' timeout'))},t);x.on('error',no);x.on('close',n=>{clearTimeout(timer);n?no(Error(c+' exit '+n)):ok(o.trim())})})}
function hash(f){return new Promise((ok,no)=>{const h=createHash('sha256'),s=createReadStream(f);s.on('data',b=>h.update(b));s.on('error',no);s.on('end',()=>ok(h.digest('hex')))})}
function blog(){const x=blogCandidates.find(p=>existsSync(join(p,'.git')));if(x)return x;const t=join(root,'.halomoon-build','HolyLinux');mkdirSync(dirname(t),{recursive:true});if(!existsSync(join(t,'.git')))run('git',['-c','http.version=HTTP/1.1','clone','https://github.com/Hole333/HolyLinux.git',t],root);return t}
function notes(b){const t=join(b,'external-notes'),rb=resolve(b),rt=resolve(t);if(!rt.startsWith(rb+sep))throw Error('unsafe notes path');rmSync(t,{recursive:true,force:true});cpSync(notesRoot,t,{recursive:true,filter:p=>!p.split(sep).includes('.git')})}
try{const b=blog();console.log('Blog: '+b);notes(b);const npm=process.platform==='win32'?'npm.cmd':'npm';run(npm,['ci','--no-audit','--no-fund'],b);run(npm,['run','build'],b,{...process.env,CI:'1'});const a=join(root,'site-local.tar.gz');run('tar',['-czf',a,'-C',join(b,'dist'),'.'],b);const commit=await cap('git',['rev-parse','HEAD'],b,10000),local=await hash(a),dest=user+'@'+host;const ssh=['-i',key,'-o','IdentitiesOnly=yes','-o','UserKnownHostsFile='+known,'-o','StrictHostKeyChecking=yes','-o','BatchMode=yes','-o','ConnectTimeout=15','-o','ServerAliveInterval=10','-o','ServerAliveCountMax=3','-o','IPQoS=throughput'];for(let n=1;n<=3;n++){try{await cap('ssh',[...ssh,dest,"pkill -u "+user+" -f 'scp -t /home/"+user+"/site.tar.gz|sftp-server' || true; rm -f /home/"+user+"/site.tar.gz"],root,30000);await cap('scp',['-O',...ssh,a,dest+':/home/'+user+'/site.tar.gz'],root,180000);break}catch(e){if(n===3)throw e;await new Promise(r=>setTimeout(r,n*5000))}}const remote=await cap('ssh',[...ssh,dest,'sha256sum /home/'+user+'/site.tar.gz'],root,30000);if(!remote.startsWith(local))throw Error('checksum mismatch');await cap('ssh',[...ssh,dest,'sudo /usr/local/sbin/deploy-halomoon '+commit],root,120000);console.log('Local deployment completed.')}catch(e){console.error(e.message||e);process.exitCode=1}
